In [ ]:
'''Objective: To combine the ML input arrays atomic position and lattice data into a single array 
                by use of radial pair distribution function'''

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [96]:
#Call data


from aflow import *

result = search(batch_size=20
        ).filter(K.Egap > 1
        ).filter(K.nspecies == 2
        ).filter(K.natoms == 2)

#print(result[7].Egap)
part = result[0:10]

len(part)
#print(result[0].species)
#for entry in result:
    #print(entry.Egap)
    


10

In [83]:
z= np.zeros([5,2], dtype=int)

for i in range(5):
    x=2
    y=3
    np.insert(z,i, [x,y])
print(z)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [72]:

help(np.insert)

Help on function insert in module numpy.lib.function_base:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out :

In [97]:
'''Define rij:  rij is a matrix which results from the dot product of the fractional postion 
coordinates and the geometry information after it has been transformed into a matrix with the 
numbers only on the diagonal and all other places 0'''

#step 1.) Dr zhu code to help transform geometry to matrix

def para2matrix(cell_para):
        """ 1x6 (a, b, c, alpha, beta, gamma) -> 3x3 representation -> """
        matrix = np.zeros([3,3])
        matrix[0][0] = cell_para[0]
        matrix[1][0] = cell_para[1]*cos(cell_para[5])
        matrix[1][1] = cell_para[1]*sin(cell_para[5])
        matrix[2][0] = cell_para[2]*cos(cell_para[4])
        matrix[2][1] = cell_para[2]*cos(cell_para[3])*sin(cell_para[4])
        matrix[2][2] = sqrt(cell_para[2]**2 - matrix[2][0]**2 - matrix[2][1]**2)
        
        return matrix

#for i in part:
    para2matrix(i)
    
#x= np.array
#





IndentationError: unindent does not match any outer indentation level (<tokenize>, line 20)

In [98]:
geo=[]

for entry in result[0:10]:
    x1= entry.geometry
    #print(X3)
    geo.append(x1)
    
#print(geo)


x1=np.asarray(geo).reshape(10,6)

print(x1)

for i in range(10):
    print(x1[i])



[[ 2.940905  2.940905  2.940905 90.       90.       90.      ]
 [ 4.585472  4.585472  4.585472 60.       60.       60.      ]
 [ 3.443548  3.443548  3.443548 60.       60.       60.      ]
 [ 3.5449    3.5449    3.5449   60.       60.       60.      ]
 [ 3.455854  3.455854  3.455854 60.       60.       60.      ]
 [ 4.057508  4.057508  4.057508 60.       60.       60.      ]
 [ 4.056879  4.056879  4.056879 60.       60.       60.      ]
 [ 4.052846  4.052846  4.052846 60.       60.       60.      ]
 [ 4.052771  4.052771  4.052771 60.       60.       60.      ]
 [ 4.497907  4.497907  4.497907 60.       60.       60.      ]]
[ 2.940905  2.940905  2.940905 90.       90.       90.      ]
[ 4.585472  4.585472  4.585472 60.       60.       60.      ]
[ 3.443548  3.443548  3.443548 60.       60.       60.      ]
[ 3.5449  3.5449  3.5449 60.     60.     60.    ]
[ 3.455854  3.455854  3.455854 60.       60.       60.      ]
[ 4.057508  4.057508  4.057508 60.       60.       60.      ]
[ 4.05687

In [126]:
from math import cos, sin, sqrt

def para2matrix(cell_para):
        """ 1x6 (a, b, c, alpha, beta, gamma) -> 3x3 representation -> """
        matrix = np.zeros([3,3])
        matrix[0][0] = cell_para[0]
        matrix[1][0] = cell_para[1]*cos(cell_para[5])
        matrix[1][1] = cell_para[1]*sin(cell_para[5])
        matrix[2][0] = cell_para[2]*cos(cell_para[4])
        matrix[2][1] = cell_para[2]*cos(cell_para[3])*sin(cell_para[4])
        matrix[2][2] = sqrt(cell_para[2]**2 - matrix[2][0]**2 - matrix[2][1]**2)
        
        return matrix
geolist= []

for i in range(10):
    geolist.append(para2matrix(x1[i]))
    
geoarray1=np.asarray(geolist).reshape(30,3) 

geoarray2 = np.split(geoarray1, [3,6,9,12,15,18,21,24,27])

print(geoarray2)



[array([[ 2.940905  ,  0.        ,  0.        ],
       [-1.31774194,  2.62915926,  0.        ],
       [-1.31774194, -1.1780569 ,  2.3504596 ]]), array([[ 4.585472  ,  0.        ,  0.        ],
       [-4.36726305, -1.39770057,  0.        ],
       [-4.36726305,  1.33118816,  0.42603398]]), array([[ 3.443548  ,  0.        ,  0.        ],
       [-3.27967981, -1.04963   ,  0.        ],
       [-3.27967981,  0.99968124,  0.31993837]]), array([[ 3.5449    ,  0.        ,  0.        ],
       [-3.37620877, -1.08052317,  0.        ],
       [-3.37620877,  1.02910429,  0.32935494]]), array([[ 3.455854  ,  0.        ,  0.        ],
       [-3.29140021, -1.053381  ,  0.        ],
       [-3.29140021,  1.00325374,  0.32108172]]), array([[ 4.057508  ,  0.        ,  0.        ],
       [-3.86442329, -1.23677153,  0.        ],
       [-3.86442329,  1.17791726,  0.3769811 ]]), array([[ 4.056879  ,  0.        ,  0.        ],
       [-3.86382422, -1.23657981,  0.        ],
       [-3.86382422,  1.177

In [127]:
pos=[]

for entry in result[0:10]:
    x2= entry.positions_fractional
    pos.append(x2)

len(pos)

X2= np.asarray(pos).reshape(20,3)

print(X2)
#print(X2[0,0])

[[ 0.5   0.5   0.5 ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.75  0.75  0.75]
 [ 0.5   0.5   0.5 ]
 [-0.   -0.   -0.  ]
 [ 0.    0.    0.  ]
 [ 0.5   0.5   0.5 ]
 [ 0.5   0.5   0.5 ]
 [-0.   -0.    0.  ]
 [ 0.   -0.    0.  ]
 [ 0.75  0.75  0.75]
 [ 0.75  0.75  0.75]
 [ 0.    0.    0.  ]
 [ 0.25  0.25  0.25]
 [ 0.    0.    0.  ]
 [ 0.25  0.25  0.25]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.5   0.5   0.5 ]]


In [135]:
rij= np.dot(X2, geoarray2) #=rij

rij.shape
print(rij)

[[[ 0.15271056  0.72555118  1.1752298 ]
  [-2.07452705 -0.0332562   0.21301699]
  [-1.55790581 -0.02497438  0.15996919]
  [-1.60375877 -0.02570944  0.16467747]
  [-1.56347321 -0.02506363  0.16054086]
  [-1.83566929 -0.02942714  0.18849055]
  [-1.83538472 -0.02942257  0.18846133]
  [-1.83356014 -0.02939332  0.18827398]
  [-1.83352621 -0.02939278  0.18827049]
  [-2.03491151 -0.03262114  0.20894918]]

 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.      

In [167]:


#Na = all the j number of atoms 
#Nb = all the steps = 50
#rij = the geo dot pos matrix
#r = the radii varying at each step by dr=0.2
#delta function between rij and r gives a 1 or 0 only
#        gives 1 only if r=rij meaning we found an atom at that r

Na= 22
Nb= 50
R=[]

r= np.arange(0.2, 10.2, 0.2)

#def delta(r, rij):
for i in np.nditer(r):
    for j in np.nditer(rij):
        if i == j:
            R.append += 1
            #R.append(incr)
print(R)

PDF =(1/Na*Nb) * sum(R)            
                

[]


In [158]:
g= np.arange(0.2,10.2, 0.2)

d= 1

for i in np.nditer(g):
    if i > d:
        print(i)
#print(g[1:3])

1.2
1.4000000000000001
1.6
1.8
2.0
2.2
2.4000000000000004
2.6000000000000005
2.8000000000000003
3.0000000000000004
3.2
3.4000000000000004
3.6000000000000005
3.8000000000000003
4.0
4.2
4.4
4.6000000000000005
4.800000000000001
5.000000000000001
5.2
5.4
5.6000000000000005
5.800000000000001
6.000000000000001
6.2
6.4
6.6000000000000005
6.800000000000001
7.000000000000001
7.2
7.4
7.6000000000000005
7.800000000000001
8.0
8.2
8.4
8.6
8.799999999999999
9.0
9.2
9.4
9.6
9.8
10.0
